# Generated by Django 5.2 on 2025-05-08 15:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_commande', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.TextField(max_length=255)),
                ('date_pub', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('download_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=191)),
                ('adresse', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this admin belongs to.', related_name='admin_set', related_query_name='admin', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='admin_permissions', related_query_name='admin', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='App.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=191)),
                ('adresse', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this utilisateur belongs to.', related_name='utilisateur_set', related_query_name='utilisateur', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this utilisateur.', related_name='utilisateur_permissions', related_query_name='utilisateur', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='App.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to='App.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='App.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='App.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_emprunt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField(default=datetime.datetime(2025, 5, 8, 15, 25, 27, 280825, tzinfo=datetime.timezone.utc))),
                ('date_fin', models.DateTimeField(default=datetime.datetime(2025, 5, 8, 15, 25, 27, 280862, tzinfo=datetime.timezone.utc))),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='App.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='App.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='App.utilisateur'),
        ),
        migrations.CreateModel(
            name='Achats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='App.livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='App.utilisateur')),
            ],
        ),
    ]
