# Generated by Django 5.2 on 2025-05-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 15, 27, 33, 132864, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 15, 27, 33, 132906, tzinfo=datetime.timezone.utc)),
        ),
    ]
