# Generated by Django 5.2 on 2025-05-10 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_emprunt_date_debut_alter_emprunt_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livre',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='panier',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='compte_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 17, 51, 43, 939717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 17, 51, 43, 939779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
